export const Enums = {
    VOTING:"VOTING",
    AIJUDGE:"AIJUDGE",
    NOJUDGE:"NOJUDGE",
    LIVE_TAB: "LIVE_TAB",
    MATCH_TIED:"MATCH_TIED",
    UPCOMING_TAB: "UPCOMING_TAB",
    WON:"WON",
    LOSE:"LOSE",
    TIED:"MATCH_TIED",
    TRANSCRIPT_TAB:"TRANSCRIPT_TAB",
    MYSTERY_TAB:"MYSTERY_TAB"



}